Description: >
    EKS Cluster for Alex Russell's Udacity capstone

Parameters:
    ClusterRoleArn:
        Description: ARN of cluster role
        Type: String
    FargateRoleArn:
        Description: ARN of Fargate exec role
        Type: String

Resources:
    Cluster:
        Type: AWS::EKS::Cluster
        Properties:
            Name: UdacityCapstoneCluster
            RoleArn: !Sub ${ClusterRoleArn}
            ResourcesVpcConfig:
                SecurityGroupIds:
                    - sg-0fa7c53ed5f027410
                    - sg-2d76dc20
                SubnetIds:
                    - subnet-0054794d
                    - subnet-1afb6545

    FargateProfile:
        Type: AWS::EKS::FargateProfile
        Properties:
            ClusterName: UdacityCapstoneCluster
            FargateProfileName: capstone-fargate
            PodexecutionRoleArn: !Sub ${FargateRoleArn}
            Selectors:
            - Namespace: default
