version: 2.1
jobs:
    build:
        docker:
            - image: node:lts-alpine3.13
        steps:
            - checkout
            - run:
                name: Build Node app
                command: |
                    npm install
                    npm run lint 
    ecr-publish:
        docker:
            - image: alpine:latest
        steps:
            - checkout
            - run:
                name: Build and push Docker image
                command: |
                    apk update
                    apk add docker -y
                    apk add --no-cache python3 py3-pip \
                    && pip3 install --upgrade pip \
                    && pip3 install \
                    awscli \
                    && rm -rf /var/cache/apk/*
                    DOCKERPATH=amrussell/udacity-capstone:latest
                    docker build -f Dockerfile -t $DOCKERPATH . -q
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
                    echo "Pushing image to $DOCKERPATH"
                    docker push $DOCKERPATH

workflows:
    default:
        jobs:
            - build
            - ecr-publish:
                requires: [build]
