version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@7.0.0

jobs:
    build:
        docker:
            - image: node:lts-alpine3.13
        steps:
            - checkout
            - run:
                name: Build Node app
                command: |
                    npm install
                    npm run lint 

workflows:
    default:
        jobs:
            - build
            - aws-ecr/build-and-push-image:
                repo: "amrussell/udacity-capstone"
                tag: "${CIRCLE_SHA1}"

