version: 1
jobs:
    build:
        docker:
            - image: node:lts-alpine3.13
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                    npm install
                    npm run lint

