version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@7.0.0
    aws-eks: circleci/aws-eks@0.2.3
    kubernetes: circleci/kubernetes@0.4.0

jobs:
    build:
        docker:
            - image: node:lts-alpine3.13
        steps:
            - checkout
            - run:
                name: Build Node app
                command: |
                    npm install
                    npm run lint 

workflows:
    default:
        jobs:
            - build
            - aws-ecr/build-and-push-image:
                requires: [build]
                account-url: ACCOUNT_URL
                repo: "amrussell/udacity-capstone"
                tag: "${CIRCLE_SHA1}"
                aws-access-key-id: AWS_ACCESS_KEY_ID
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY
                create-repo: true
                region: AWS_REGION
            - aws-eks/update-container-image:
                cluster-name: UdacityCapstoneCluster
                container-image-updates: alex-udacity-capstone=amrussell/udacity-capstone:${CIRCLE_SHA1}
                requires: [create-deployment]
                aws-region: ${AWS_REGION}
                resource-name: deployment.apps/alex-udacity-capstone
                get-rollout-status: true

