kind: Deployment 
apiVersion: apps/v1 
metadata:
  name: alex-udacity-capstone
spec:
    replicas: 2

    selector:
        matchLabels: 
            app: capstone 

    template:
        metadata:
            labels:
                app: capstone
        spec:
            containers:
            - name: capstone
              image: amrussell/udacity-capstone
              ports:
              - containerPort: 3000
